name: shayniss
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1
  video_player: ^2.8.2
  json_annotation: ^4.9.0
  video_thumbnail: ^0.5.3
  uuid: ^4.3.3
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  intl: ^0.18.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  provider: ^6.1.1
  path_provider: ^2.1.2
  http: ^1.1.0
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.18
  file_picker: ^6.2.0
  path: ^1.8.3
  audioplayers: ^6.1.2
  geolocator: ^13.0.2
  app_links: ^3.5.1
  share_plus: ^7.2.1
  fl_chart: ^0.65.0
  record: ^4.4.4
  open_file: ^3.3.2
  syncfusion_flutter_charts: ^23.2.7
  pdf: ^3.10.7
  shimmer: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/services/
    - assets/icons/
    - assets/sounds/
    - assets/fonts/
